"""phase 2: email OAuth, durable sync jobs, CV extraction

Revision ID: 0002_email_sync_oauth_clients
Revises: 0001_initial_schema
Create Date: 2026-09-27 19:05:08.170579+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_email_sync_oauth_clients'
down_revision: Union[str, Sequence[str], None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_client_configs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('tenant', sa.String(length=120), nullable=True),
    sa.Column('redirect_uri', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_client_configs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_client_configs')),
    sa.UniqueConstraint('user_id', 'provider', name='uq_oauth_client_configs_owner_provider')
    )
    with op.batch_alter_table('oauth_client_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_client_configs_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_client_configs_user_id'), ['user_id'], unique=False)

    op.create_table('sync_jobs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('account_ids', sa.JSON(), nullable=False),
    sa.Column('accounts_total', sa.Integer(), nullable=False),
    sa.Column('accounts_processed', sa.Integer(), nullable=False),
    sa.Column('messages_scanned', sa.Integer(), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('jobs_new', sa.Integer(), nullable=False),
    sa.Column('jobs_duplicate', sa.Integer(), nullable=False),
    sa.Column('messages_skipped', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=120), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sync_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_jobs'))
    )
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_sync_jobs_status_lease', ['status', 'lease_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_jobs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_sync_jobs_user_requested', ['user_id', 'requested_at'], unique=False)

    op.create_table('processed_messages',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mail_account_id', sa.Uuid(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('sender', sa.String(length=320), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mail_account_id'], ['mail_accounts.id'], name=op.f('fk_processed_messages_mail_account_id_mail_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_processed_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_messages')),
    sa.UniqueConstraint('mail_account_id', 'provider_message_id', name='uq_processed_messages_account_message')
    )
    with op.batch_alter_table('processed_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_messages_mail_account_id'), ['mail_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_messages_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_processed_messages_user_processed', ['user_id', 'processed_at'], unique=False)

    op.create_table('sync_checkpoints',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mail_account_id', sa.Uuid(), nullable=False),
    sa.Column('cursor_kind', sa.String(length=20), nullable=False),
    sa.Column('cursor_value', sa.Text(), nullable=True),
    sa.Column('cursor_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initial_sync_completed', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_class', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mail_account_id'], ['mail_accounts.id'], name=op.f('fk_sync_checkpoints_mail_account_id_mail_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sync_checkpoints_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_checkpoints')),
    sa.UniqueConstraint('mail_account_id', name='uq_sync_checkpoints_account')
    )
    with op.batch_alter_table('sync_checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_checkpoints_mail_account_id'), ['mail_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_checkpoints_user_id'), ['user_id'], unique=False)

    op.create_table('sync_job_accounts',
    sa.Column('sync_job_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mail_account_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('messages_scanned', sa.Integer(), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('jobs_new', sa.Integer(), nullable=False),
    sa.Column('jobs_duplicate', sa.Integer(), nullable=False),
    sa.Column('messages_skipped', sa.Integer(), nullable=False),
    sa.Column('error_class', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mail_account_id'], ['mail_accounts.id'], name=op.f('fk_sync_job_accounts_mail_account_id_mail_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], name=op.f('fk_sync_job_accounts_sync_job_id_sync_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sync_job_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_job_accounts')),
    sa.UniqueConstraint('sync_job_id', 'mail_account_id', name='uq_sync_job_accounts_job_account')
    )
    with op.batch_alter_table('sync_job_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_job_accounts_mail_account_id'), ['mail_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_job_accounts_sync_job_id'), ['sync_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_job_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('job_sources',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('mail_account_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('sender', sa.String(length=320), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_sources_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mail_account_id'], ['mail_accounts.id'], name=op.f('fk_job_sources_mail_account_id_mail_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_job_sources_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_sources')),
    sa.UniqueConstraint('job_id', 'provider_message_id', name='uq_job_sources_job_message')
    )
    with op.batch_alter_table('job_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_sources_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_job_sources_user_account', ['user_id', 'mail_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_sources_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extraction_status', sa.String(length=30), server_default='pending', nullable=False))
        batch_op.add_column(sa.Column('extraction_warning', sa.String(length=300), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_normalized', sa.String(length=600), nullable=True))
        batch_op.add_column(sa.Column('fingerprint_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('description_status', sa.String(length=30), server_default='ok', nullable=False))
        batch_op.create_index(batch_op.f('ix_jobs_fingerprint_hash'), ['fingerprint_hash'], unique=False)
        batch_op.create_unique_constraint('uq_jobs_owner_fingerprint', ['user_id', 'fingerprint_hash'])

    with op.batch_alter_table('mail_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_account_id', sa.String(length=320), nullable=True))
        batch_op.add_column(sa.Column('token_cache_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('filters', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
        batch_op.add_column(sa.Column('initial_sync_completed', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('mail_account_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_oauth_states_session_id'), ['session_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_oauth_states_session_id_sessions'), 'sessions', ['session_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_oauth_states_mail_account_id_mail_accounts'), 'mail_accounts', ['mail_account_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_oauth_states_mail_account_id_mail_accounts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_oauth_states_session_id_sessions'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_oauth_states_session_id'))
        batch_op.drop_column('mail_account_id')
        batch_op.drop_column('session_id')

    with op.batch_alter_table('mail_accounts', schema=None) as batch_op:
        batch_op.drop_column('initial_sync_completed')
        batch_op.drop_column('filters')
        batch_op.drop_column('token_cache_encrypted')
        batch_op.drop_column('provider_account_id')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_jobs_owner_fingerprint', type_='unique')
        batch_op.drop_index(batch_op.f('ix_jobs_fingerprint_hash'))
        batch_op.drop_column('description_status')
        batch_op.drop_column('fingerprint_hash')
        batch_op.drop_column('url_normalized')

    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.drop_column('extraction_warning')
        batch_op.drop_column('extraction_status')

    with op.batch_alter_table('job_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_sources_user_id'))
        batch_op.drop_index('ix_job_sources_user_account')
        batch_op.drop_index(batch_op.f('ix_job_sources_job_id'))

    op.drop_table('job_sources')
    with op.batch_alter_table('sync_job_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_job_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_sync_job_accounts_sync_job_id'))
        batch_op.drop_index(batch_op.f('ix_sync_job_accounts_mail_account_id'))

    op.drop_table('sync_job_accounts')
    with op.batch_alter_table('sync_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_checkpoints_user_id'))
        batch_op.drop_index(batch_op.f('ix_sync_checkpoints_mail_account_id'))

    op.drop_table('sync_checkpoints')
    with op.batch_alter_table('processed_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_processed_messages_user_processed')
        batch_op.drop_index(batch_op.f('ix_processed_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_processed_messages_mail_account_id'))

    op.drop_table('processed_messages')
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_jobs_user_requested')
        batch_op.drop_index(batch_op.f('ix_sync_jobs_user_id'))
        batch_op.drop_index('ix_sync_jobs_status_lease')
        batch_op.drop_index(batch_op.f('ix_sync_jobs_status'))

    op.drop_table('sync_jobs')
    with op.batch_alter_table('oauth_client_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_client_configs_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_client_configs_provider'))

    op.drop_table('oauth_client_configs')
    # ### end Alembic commands ###
