"""phase 3: LLM scoring, Telegram notifications, scheduled scans

Revision ID: 0003_phase3_scoring_telegram_scheduler
Revises: 0002_email_sync_oauth_clients
Create Date: 2026-09-28 16:31:20.911345+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_phase3_scoring_telegram_scheduler'
down_revision: Union[str, Sequence[str], None] = '0002_email_sync_oauth_clients'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('cv_id', sa.Uuid(), nullable=True),
    sa.Column('cv_checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], name=op.f('fk_cv_profiles_cv_id_cvs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cv_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cv_profiles')),
    sa.UniqueConstraint('user_id', name='uq_cv_profiles_owner')
    )
    with op.batch_alter_table('cv_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cv_profiles_cv_checksum'), ['cv_checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_cv_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('llm_usage',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_class', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.String(length=300), nullable=True),
    sa.Column('is_mock', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_llm_usage_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_llm_usage_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage'))
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index('ix_llm_usage_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_user_id'), ['user_id'], unique=False)

    op.create_table('scoring_items',
    sa.Column('sync_job_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=True),
    sa.Column('cv_checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_class', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.String(length=400), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_scoring_items_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['job_matches.id'], name=op.f('fk_scoring_items_match_id_job_matches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], name=op.f('fk_scoring_items_sync_job_id_sync_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scoring_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_items')),
    sa.UniqueConstraint('sync_job_id', 'job_id', name='uq_scoring_items_job_entry')
    )
    with op.batch_alter_table('scoring_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scoring_items_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scoring_items_sync_job_id'), ['sync_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scoring_items_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_scoring_items_user_status', ['user_id', 'status'], unique=False)

    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('experience_match', sa.String(length=20), server_default='unknown', nullable=False))
        batch_op.add_column(sa.Column('location_match', sa.String(length=20), server_default='unknown', nullable=False))
        batch_op.add_column(sa.Column('work_mode_match', sa.String(length=20), server_default='unknown', nullable=False))
        batch_op.add_column(sa.Column('title_match', sa.String(length=20), server_default='unknown', nullable=False))
        batch_op.add_column(sa.Column('match_details', sa.JSON(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('insufficient_information', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('analysis_status', sa.String(length=20), server_default='pending', nullable=False))
        batch_op.add_column(sa.Column('analysis_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('analysis_attempts', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('cv_checksum', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('prompt_version', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_job_matches_analysis_status'), ['analysis_status'], unique=False)

    with op.batch_alter_table('notification_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_message_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('dedupe_key', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('error_class', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_notifications_owner_dedupe', ['user_id', 'dedupe_key'])

    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=20), server_default='mail_scan', nullable=False))
        batch_op.add_column(sa.Column('payload', sa.JSON(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('progress', sa.JSON(), server_default='{}', nullable=False))
        batch_op.create_index(batch_op.f('ix_sync_jobs_kind'), ['kind'], unique=False)

    with op.batch_alter_table('telegram_integrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_error_class', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_notification_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_scan_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_auto_scan_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('auto_scan_failures', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_user_preferences_next_scan_at'), ['next_scan_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_next_scan_at'))
        batch_op.drop_column('auto_scan_failures')
        batch_op.drop_column('last_auto_scan_at')
        batch_op.drop_column('next_scan_at')

    with op.batch_alter_table('telegram_integrations', schema=None) as batch_op:
        batch_op.drop_column('last_notification_at')
        batch_op.drop_column('last_checked_at')
        batch_op.drop_column('last_error_class')

    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_jobs_kind'))
        batch_op.drop_column('progress')
        batch_op.drop_column('payload')
        batch_op.drop_column('kind')

    with op.batch_alter_table('notification_history', schema=None) as batch_op:
        batch_op.drop_constraint('uq_notifications_owner_dedupe', type_='unique')
        batch_op.drop_column('error_class')
        batch_op.drop_column('dedupe_key')
        batch_op.drop_column('attempts')
        batch_op.drop_column('provider_message_id')

    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_matches_analysis_status'))
        batch_op.drop_column('prompt_version')
        batch_op.drop_column('cv_checksum')
        batch_op.drop_column('analyzed_at')
        batch_op.drop_column('analysis_attempts')
        batch_op.drop_column('analysis_error')
        batch_op.drop_column('analysis_status')
        batch_op.drop_column('insufficient_information')
        batch_op.drop_column('match_details')
        batch_op.drop_column('title_match')
        batch_op.drop_column('work_mode_match')
        batch_op.drop_column('location_match')
        batch_op.drop_column('experience_match')
        batch_op.drop_column('confidence')

    with op.batch_alter_table('scoring_items', schema=None) as batch_op:
        batch_op.drop_index('ix_scoring_items_user_status')
        batch_op.drop_index(batch_op.f('ix_scoring_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_scoring_items_sync_job_id'))
        batch_op.drop_index(batch_op.f('ix_scoring_items_job_id'))

    op.drop_table('scoring_items')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_user_id'))
        batch_op.drop_index('ix_llm_usage_user_created')

    op.drop_table('llm_usage')
    with op.batch_alter_table('cv_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cv_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_cv_profiles_cv_checksum'))

    op.drop_table('cv_profiles')
    # ### end Alembic commands ###
